### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by Anshuljai** [Samue-l1/Classic-v3-BUG#71]
When i do npm start it got error like this

`Unsupported platform/architecture: android-arm64`

![Screenshot_2024-07-03-20-34-52-900_com termux](https://github.com/Samue-l1/Classic-v3-BUG/assets/24720160/df640bfe-630a-4cfc-bb0e-c40ff35ab4c6)

**Comment by anonphoenix007** [comment]
Hello 👋
You can try installing Ubuntu on your termux if you know the workaround ,Try this below commands to install ubuntu and install Classic-v3-BUG which I have tested.

$ apt update && apt upgrade -y
$ apt install wget curl tar proot-distro -y
$ proot-distro list
$ proot-distro install ubuntu

You can choose to install Debian or arch or your preferred system,I always go for the Debian based OS or Arch Linux.
if Ubuntu is successfully installed ,login with

$ proot-distro login ubuntu

You will get into Ubuntu root shell with proot-distro.

then retry the commands to setup Classic-v3-BUG ,remember to update and upgrade and have fun,Termux won't run some programs so it's preferable to use another operating system setup on it,Good luck.
